import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "beercss";
import "material-dynamic-colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <nav className="bottom">
          <a>
            <i>home</i>
            <div>Home</div>
          </a>
          <a>
            <i>search</i>
            <div>Search</div>
          </a>
          <a>
            <i>share</i>
            <div>Share</div>
          </a>
        </nav> */}

        <main className="responsive">
          {children}
        </main>
      </body>
    </html>
  );
}
